# Generated by Django 2.1.4 on 2020-03-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GWCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=64)),
                ('candidate_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('ra', models.CharField(max_length=64)),
                ('dec', models.CharField(max_length=64)),
                ('websniff_url', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
