# Generated by Django 2.1.4 on 2020-03-09 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sniffapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gwcandidate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gwcandidate',
            name='websniff_url',
        ),
    ]
