# Generated by Django 2.1.4 on 2020-03-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sniffapp', '0002_auto_20200309_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gwcandidate',
            name='field',
        ),
    ]
