# Generated by Django 2.1.4 on 2020-03-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniffapp', '0003_remove_gwcandidate_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='GWCandidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=64)),
                ('ra', models.CharField(max_length=64)),
                ('dec', models.CharField(max_length=64)),
                ('field', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='GWCandidate',
        ),
    ]
