# Generated by Django 2.1.4 on 2020-03-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sniffapp', '0004_auto_20200313_2209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GWCandidates',
            new_name='GWCandidate',
        ),
    ]
