# Generated by Django 2.1.4 on 2020-03-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sniffapp', '0005_auto_20200313_2211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GWCandidate',
        ),
    ]
