# Generated by Django 2.1.4 on 2020-03-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sniffapp', '0007_gwcandidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GWCandidate',
        ),
    ]
