# Generated by Django 2.1.4 on 2020-03-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sniffapp', '0009_gwcandidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GWCandidate',
        ),
    ]
