# Generated by Django 2.1.4 on 2020-03-22 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sniffapp', '0010_delete_gwcandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GWCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=64)),
                ('ra', models.CharField(max_length=64)),
                ('dec', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='GWevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gwevent', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='GWfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=64)),
                ('gwevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sniffapp.GWevent')),
            ],
        ),
        migrations.AddField(
            model_name='gwcandidate',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sniffapp.GWfield'),
        ),
        migrations.AddField(
            model_name='gwcandidate',
            name='gwevent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sniffapp.GWevent'),
        ),
    ]
