# Generated by Django 2.1.4 on 2020-03-22 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sniffapp', '0011_auto_20200322_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwcandidate',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sniffapp.GWfield'),
        ),
        migrations.AlterField(
            model_name='gwcandidate',
            name='gwevent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sniffapp.GWevent'),
        ),
        migrations.AlterField(
            model_name='gwfield',
            name='gwevent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sniffapp.GWevent'),
        ),
    ]
