# Generated by Django 2.1.4 on 2020-03-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sniffapp', '0014_auto_20200322_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gwcandidate',
            name='field',
        ),
        migrations.RemoveField(
            model_name='gwcandidate',
            name='gwevent',
        ),
        migrations.RemoveField(
            model_name='gwfield',
            name='gwevent',
        ),
        migrations.DeleteModel(
            name='GWCandidate',
        ),
        migrations.DeleteModel(
            name='GWevent',
        ),
        migrations.DeleteModel(
            name='GWfield',
        ),
    ]
