# Generated by Django 2.1.4 on 2020-03-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniffapp', '0017_gwcandidate_percentlikely'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwcandidate',
            name='percentlikely',
            field=models.FloatField(default=0),
        ),
    ]
