# Generated by Django 2.1.4 on 2020-03-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniffapp', '0018_auto_20200325_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='gwcandidate',
            name='percentpossible',
            field=models.FloatField(default=0),
        ),
    ]
