# Generated by Django 2.1.4 on 2020-04-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniffapp', '0019_gwcandidate_percentpossible'),
    ]

    operations = [
        migrations.AddField(
            model_name='gwcandidate',
            name='snr',
            field=models.FloatField(default=0),
        ),
    ]
